server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:oracle:thin:@aquacoemployer_high?TNS_ADMIN=Rutawallet
    username: user
    password: contra
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
